# ---
# - name: Update apt cache
#   apt:
#     update_cache: yes
#   become: yes

# - name: Upgrade packages
#   apt:
#     upgrade: dist
#   become: yes

# - name: Install essential packages
#   apt:
#     name:
#       - curl
#       - wget
#       - vim
#       - git
#       - qemu-guest-agent
#       - net-tools
#     state: present
#   become: yes
---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Upgrade packages
  apt:
    upgrade: dist
  become: yes

- name: Uninstall essential packages with purge
  apt:
    name:
      - curl
      - wget
      - vim
      - git
      - qemu-guest-agent
      - net-tools
    state: absent
    purge: yes
  become: yes
