---
- name: Upgrade APT
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: Update the package information
  ansible.builtin.package:
    update_cache: true

- name: Install essential packages
  ansible.builtin.package :
    name:
      - curl
      - wget
      - vim
      - git
      - qemu-guest-agent
      - net-tools
    state: present
  become: yes
  
- name: Install qemu-guest-agent
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present

- name: Enable the qemu-guest-agent service
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
