---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Upgrade packages
  apt:
    upgrade: dist
  become: yes

- name: Install essential packages
  apt:
    name:
      - curl
      - wget
      - vim
      - git
    state: present
  become: yes
