---
- name: Download k3s installation script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'
  become: yes

- name: Install k3s master
  shell: |
    INSTALL_K3S_EXEC="server --tls-san {{ ansible_host }}" /tmp/k3s_install.sh
  args:
    creates: /usr/local/bin/k3s
  become: yes

- name: Retrieve k3s join token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token_output
  become: yes

- name: Set join token fact for workers
  set_fact:
    k3s_token: "{{ k3s_token_output.stdout }}"
