---
- name: Download k3s installation script on worker
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'
  become: yes

- name: Install k3s worker and join cluster
  shell: |
    K3S_URL=https://{{ hostvars['master-node'].ansible_host }}:6443 K3S_TOKEN={{ hostvars['master-node'].k3s_token }} /tmp/k3s_install.sh
  args:
    creates: /usr/local/bin/k3s
  become: yes
